version: "3.4"

services:
  docker-nginx:
    image: nginx:alpine
    container_name: docker-nginx
    working_dir: /application
    restart: always
    depends_on:
      - app-laravel
      # - app-websockets
      - docker-mail
      - docker-mysql
      - docker-redis
    networks:
      - default
    ports:
      - "80:80"
    volumes:
      - ../laravel:/application:delegated
      - ../logs/nginx:/var/log/nginx
      - ./build/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro

  app-laravel:
    build: ./build/laravel
    container_name: app-laravel
    working_dir: /application
    restart: always
    networks:
      - default
    links:
      - docker-mail
      - docker-mysql
      - docker-redis
    volumes:
      - nfs-laravel:/application:delegated
      - ../laravel/storage/logs:/application/storage/logs
      - ./build/laravel/php-overrides.ini:/usr/local/etc/php/conf.d/99-overrides.ini

  # # app-websockets:
  # # 	image: @todo:latest
  # # 	container_name: websockets
  # # 	restart: always
  # # 	networks:
  # # 		- default
  # # 	ports:
  # # 		- "6001:6001"
  # # 	links:
  # # 		- docker-redis

  docker-mail:
    image: mailhog/mailhog:latest
    container_name: docker-mail
    restart: always
    ports:
      - "${MAIL_PORT}:1025"
      - "${MAIL_MAILHOG_WEBUI_PORT}:8025"

  mysql:
    image: mysql:5.7
    container_name: docker-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:3306"
    networks:
      - default
    volumes:
      - data-mysql:/var/lib/mysql
      - ./build/mysql/initial.sql:/docker-entrypoint-initdb.d/${DB_DATABASE}.sql:cached

  docker-redis:
    image: redis:alpine
    container_name: docker-redis
    restart: always
    ports:
      - "${REDIS_PORT}"
    networks:
      - default
    volumes:
      - data-redis:/data

networks:
  default:
    driver: bridge

volumes:
  nfs-laravel:
    driver: local
    driver_opts:
      type: nfs
      o: addr=host.docker.internal,rw,nolock,hard,nointr,nfsvers=3
      device: ":$PWD/laravel"
  data-mysql:
    name: volume-mysql
  data-redis:
    name: volume-redis
